# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95945448651144efcc9eb85647ef4f88"
name = "AutoVid"
handle = "autovid"
application_url = "https://lite-oxford-atom-promised.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lite-oxford-atom-promised.trycloudflare.com/auth/callback",
  "https://lite-oxford-atom-promised.trycloudflare.com/auth/shopify/callback",
  "https://lite-oxford-atom-promised.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://lite-oxford-atom-promised.trycloudflare.com/api"
subpath = "autovid"
prefix = "a"

[pos]
embedded = false
