# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95945448651144efcc9eb85647ef4f88"
name = "AutoVid"
handle = "autovid"
application_url = "https://app.autovidapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://app.autovidapp.com/auth/callback",
  "https://app.autovidapp.com/auth/shopify/callback",
  "https://app.autovidapp.com/api/auth/callback"
]

[app_proxy]
url = "https://app.autovidapp.com/api"
subpath = "autovid"
prefix = "a"

[pos]
embedded = false
